### ISSUE TITLE
Help Needed!

### ISSUE THREAD

**Issue by TownyMontana** [aneurinprice/mogno#1]
How to fix this issue:

Traceback (most recent call last):
  File "C:\Users\xxxxx\mogno-main\main.py", line 46, in <module>
    config, plex = LoadConfig()
                   ^^^^^^^^^^^^
  File "C:\Users\xxxxx\mogno-main\main.py", line 12, in LoadConfig
    plex = PlexServer(config['PlexHost'], config['PlexToken'])
                      ~~~~~~^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by aneurinprice** [comment]
Hi!

Please provide your python version and the version of plexapi module

**Comment by aneurinprice** [comment]
and the contents of your config file (please do not include secret values)

**Comment by aneurinprice** [comment]
Closing due to lack of response
